exclude: ['posts']
url: https://povcode.com
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme
 - jekyll-sitemap
 - jekyll-paginate

remote_theme: jekyll/minima

#theme: minima
locale: "en-US"
title: "Ramazan Cetin"
author:
  name: Ramazan ÇETİN
  email: xxxx@xxx.com
  type: person
  
description: >
  I'm a software enginer.  

paginate: 20
show_excerpts: true
google_analytics: G-ZPHHT8GE5Z
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate_path: /blog/:num

minima:
  skin: classic
  date_format: "%b %-d, %Y"
  social_links:
    twitter: ramazanlcetin
    github: ramazanlcetin
    linkedin: cetinramazan
